// Nepal Administrative Data
// Provinces → Districts → Municipalities

export const NEPAL_DATA = {
  "Koshi": {
    "Taplejung": ["Taplejung Municipality", "Phungling Municipality", "Sirijunga Rural Municipality", "Meringden Rural Municipality", "Mikwakhola Rural Municipality", "Sidingba Rural Municipality", "Phaktanglung Rural Municipality", "Maiwakhola Rural Municipality", "Yangwarak Rural Municipality"],
    "Sankhuwasabha": ["Chainpur Municipality", "Khandbari Municipality", "Dharmadevi Municipality", "Panchkhapan Municipality", "Madi Municipality", "Sabhapokhari Rural Municipality", "Silichong Rural Municipality", "Makalu Rural Municipality", "Chichila Rural Municipality", "Hatuwagadhi Rural Municipality"],
    "Bhojpur": ["Bhojpur Municipality", "Shadananda Municipality", "Arun Rural Municipality", "Tyamkemaiyung Rural Municipality", "Hatuwagadhi Rural Municipality", "Ramprasad Rai Rural Municipality", "Pauwadungma Rural Municipality"],
    "Dhankuta": ["Dhankuta Municipality", "Pakhribas Municipality", "Mahalaxmi Municipality", "Chhathar Jorpati Rural Municipality", "Sahidbhumi Rural Municipality", "Sangurigadhi Rural Municipality"],
    "Terhathum": ["Myanglung Municipality", "Laligurans Municipality", "Aathrai Triveni Rural Municipality", "Chhathar Rural Municipality", "Ferrong Rural Municipality", "Phedap Rural Municipality"],
    "Solukhumbu": ["Solududhkunda Municipality", "Namche Rural Municipality", "Khumjung Rural Municipality", "Likhupike Rural Municipality", "Sotang Rural Municipality", "Thulung Dudhkoshi Rural Municipality", "Mapya Dudhkoshi Rural Municipality", "Mahakulung Rural Municipality", "Khumbupasanglahmu Rural Municipality"],
    "Okhaldhunga": ["Siddhicharan Municipality", "Molung Rural Municipality", "Likhu Rural Municipality", "Sunkoshi Rural Municipality", "Champadevi Rural Municipality", "Khijidemba Rural Municipality", "Manebhanjyang Rural Municipality"],
    "Khotang": ["Diktel Rupakot Majhuwagadhi Municipality", "Halesi Tuwachung Municipality", "Khotehang Rural Municipality", "Aiselukharka Rural Municipality", "Barahpokhara Rural Municipality", "Diprung Chuichumma Rural Municipality", "Kepilasagadhi Rural Municipality", "Rawabesi Rural Municipality", "Sakela Rural Municipality"],
    "Udayapur": ["Triyuga Municipality", "Katari Municipality", "Belaka Municipality", "Udayapurgadhi Rural Municipality", "Chaudandigadhi Municipality", "Rautamai Rural Municipality", "Tapli Rural Municipality"],
    "Sunsari": ["Itahari Sub-Metropolitan City", "Dharan Sub-Metropolitan City", "Inaruwa Municipality", "Barahkshetra Municipality", "Duhabi Municipality", "Ramdhuni Municipality", "Harinagar Rural Municipality", "Barju Rural Municipality", "Gadhi Rural Municipality", "Bhokraha Narsingh Rural Municipality"],
    "Morang": ["Biratnagar Metropolitan City", "Urlabari Municipality", "Sundar Haraicha Municipality", "Rangeli Municipality", "Pathari-Shanischare Municipality", "Letang Municipality", "Belbari Municipality", "Gramin Municipality", "Jahada Rural Municipality", "Kanepokhari Rural Municipality", "Kerabari Rural Municipality", "Miklajung Rural Municipality", "Ratuwamai Rural Municipality"],
    "Jhapa": ["Birtamod Municipality", "Mechinagar Municipality", "Damak Municipality", "Kankai Municipality", "Bhadrapur Municipality", "Shivasataxi Municipality", "Arjundhara Municipality", "Gauriganj Rural Municipality", "Haldibari Rural Municipality", "Jhapa Rural Municipality", "Kachankawal Rural Municipality", "Kamal Rural Municipality", "Buddhashanti Rural Municipality", "Barhadashi Rural Municipality"],
    "Ilam": ["Ilam Municipality", "Deumai Municipality", "Mai Municipality", "Suryodaya Municipality", "Rong Rural Municipality", "Mangsebung Rural Municipality", "Chulachuli Rural Municipality", "Sandakpur Rural Municipality", "Phakphokthum Rural Municipality"]
  },
  "Madhesh": {
    "Parsa": ["Birgunj Metropolitan City", "Pokhariya Municipality", "Bahudarmai Municipality", "Parsagadhi Municipality", "Paterwa Sugauli Rural Municipality", "Jagarnathpur Rural Municipality", "Kalikamai Rural Municipality", "Bindabasini Rural Municipality", "Thori Rural Municipality", "Chhipaharmai Rural Municipality"],
    "Bara": ["Kalaiya Sub-Metropolitan City", "Jitpur Simara Sub-Metropolitan City", "Kolhabi Municipality", "Nijgadh Municipality", "Mahagadhimai Municipality", "Prasauni Municipality", "Pacharauta Municipality", "Pheta Rural Municipality", "Adarsha Kotwal Rural Municipality", "Suvarna Rural Municipality", "Devtal Rural Municipality", "Karaiyamai Rural Municipality"],
    "Rautahat": ["Gaur Municipality", "Chandrapur Municipality", "Garuda Municipality", "Baudihawa Municipality", "Ishnath Municipality", "Maulapur Municipality", "Rajpur Municipality", "Rajdevi Municipality", "Brindaban Rural Municipality", "Dewahi Gonahi Rural Municipality", "Durga Bhagwati Rural Municipality", "Gujara Rural Municipality", "Katahariya Rural Municipality", "Madhav Narayan Rural Municipality", "Paroha Rural Municipality", "Phatuwa Bijayapur Rural Municipality", "Yemunamai Rural Municipality"],
    "Sarlahi": ["Malangwa Municipality", "Lalbandi Municipality", "Bagmati Municipality", "Balara Municipality", "Barahathwa Municipality", "Godaita Municipality", "Haripur Municipality", "Haripurwa Municipality", "Ishworpur Municipality", "Kabilasi Municipality", "Chakraghatta Rural Municipality", "Dhankaul Rural Municipality", "Bishnupur Rural Municipality", "Bramhapuri Rural Municipality"],
    "Mahottari": ["Jaleshwar Municipality", "Bardibas Municipality", "Gaushala Municipality", "Loharpatti Municipality", "Manara Shiswa Municipality", "Matihani Municipality", "Ramgopalpur Municipality", "Aurahi Rural Municipality", "Bhangaha Municipality", "Ekdara Rural Municipality", "Mahottari Rural Municipality", "Pipra Rural Municipality", "Samsi Rural Municipality", "Sonama Rural Municipality"],
    "Dhanusha": ["Janakpur Sub-Metropolitan City", "Dhanusha Rural Municipality", "Dhanusadham Municipality", "Ganeshman Charnath Municipality", "Mithila Municipality", "Mithila Bihari Municipality", "Nagarain Municipality", "Sahidnagar Municipality", "Sabaila Municipality", "Bideha Rural Municipality", "Bateshwar Rural Municipality", "Aaurahi Rural Municipality", "Janaknandini Rural Municipality", "Mukhiyapatti Musaharniya Rural Municipality", "Lakshminiya Rural Municipality"],
    "Siraha": ["Siraha Municipality", "Lahan Municipality", "Dhangadhimai Municipality", "Golbazar Municipality", "Mirchaiya Municipality", "Sukhipur Municipality", "Kartik Thapa Rural Municipality", "Aurahi Rural Municipality", "Naraha Rural Municipality", "Bariyarpatti Rural Municipality", "Bhagawanpur Rural Municipality", "Bishnupur Rural Municipality", "Arnama Rural Municipality", "Sakhuwanankarkatti Rural Municipality"],
    "Saptari": ["Rajbiraj Municipality", "Kanchanrup Municipality", "Shambhunath Municipality", "Khadak Municipality", "Dakneshwori Municipality", "Tirahut Municipality", "Saptakoshi Rural Municipality", "Agnisair Krishna Savaran Rural Municipality", "Balan-Bihul Rural Municipality", "Belhi Chapena Rural Municipality", "Bishnupur Rural Municipality", "Chhinnamasta Rural Municipality", "Hanumannagar Kankalini Municipality", "Mahadeva Rural Municipality", "Rajgadh Rural Municipality", "Rupani Rural Municipality", "Tilathi Koiladi Rural Municipality"]
  },
  "Bagmati": {
    "Kathmandu": ["Kathmandu Metropolitan City", "Kirtipur Municipality", "Chandragiri Municipality", "Dakshinkali Municipality", "Gokarneshwar Municipality", "Kageshwari-Manohara Municipality", "Nagarjun Municipality", "Shankharapur Municipality", "Tokha Municipality", "Budhanilkantha Municipality", "Tarakeshwar Municipality"],
    "Lalitpur": ["Lalitpur Metropolitan City", "Mahalaxmi Municipality", "Godawari Municipality", "Bagmati Rural Municipality", "Konjyosom Rural Municipality"],
    "Bhaktapur": ["Bhaktapur Municipality", "Madhyapur Thimi Municipality", "Changunarayan Municipality", "Suryabinayak Municipality"],
    "Sindhupalchok": ["Chautara Sangachokgadhi Municipality", "Bahrabise Municipality", "Melamchi Municipality", "Barhabise Municipality", "Bhotekoshi Rural Municipality", "Helambu Rural Municipality", "Indrawati Rural Municipality", "Jugal Rural Municipality", "Listikot Rural Municipality", "Sunkoshi Rural Municipality", "Tripurasundari Rural Municipality"],
    "Rasuwa": ["Kalika Rural Municipality", "Gosaikunda Rural Municipality", "Naukunda Rural Municipality", "Parbatikunda Rural Municipality", "Uttargaya Rural Municipality"],
    "Nuwakot": ["Bidur Municipality", "Belkotgadhi Municipality", "Tadi Rural Municipality", "Dupcheshwar Rural Municipality", "Kakani Rural Municipality", "Kispang Rural Municipality", "Suryagadhi Rural Municipality", "Shivapuri Rural Municipality", "Myagang Rural Municipality", "Likhu Rural Municipality", "Tarkeshwar Rural Municipality"],
    "Dhading": ["Nilkantha Municipality", "Benighat Rorang Rural Municipality", "Gajuri Rural Municipality", "Galchi Rural Municipality", "Jwalamukhi Rural Municipality", "Khaniyabas Rural Municipality", "Netrawati Dabjong Rural Municipality", "Rubi Valley Rural Municipality", "Siddhalek Rural Municipality", "Thakre Rural Municipality", "Tripura Sundari Rural Municipality"],
    "Makwanpur": ["Hetauda Sub-Metropolitan City", "Bhimphedi Rural Municipality", "Bakaiya Rural Municipality", "Bagmati Rural Municipality", "Indrasarowar Rural Municipality", "Kailash Rural Municipality", "Makawanpurgadhi Rural Municipality", "Manahari Rural Municipality", "Raksirang Rural Municipality", "Thaha Municipality"],
    "Chitwan": ["Bharatpur Metropolitan City", "Ratnanagar Municipality", "Khairahani Municipality", "Madi Municipality", "Rapti Municipality", "Bharatpur Municipality", "Ichchhakamana Rural Municipality"],
    "Ramechhap": ["Manthali Municipality", "Ramechhap Municipality", "Umakunda Rural Municipality", "Gokulaganga Rural Municipality", "Khandadevi Rural Municipality", "Doramba Rural Municipality", "Sunapati Rural Municipality", "Likhu Tamakoshi Rural Municipality"],
    "Dolakha": ["Charikot Municipality", "Jiri Municipality", "Baiteshwar Rural Municipality", "Bigu Rural Municipality", "Bhimeshwar Municipality", "Gaurishankar Rural Municipality", "Kalinchok Rural Municipality", "Melung Rural Municipality", "Shailung Rural Municipality", "Tamakoshi Rural Municipality"],
    "Kavrepalanchok": ["Dhulikhel Municipality", "Banepa Municipality", "Panauti Municipality", "Namobuddha Municipality", "Panchkhal Municipality", "Mandandeupur Municipality", "Khanikhola Rural Municipality", "Mahabharat Rural Municipality", "Temal Rural Municipality", "Roshi Rural Municipality", "Bethanchok Rural Municipality", "Bhumlu Rural Municipality", "Chaurideurali Rural Municipality"]
  },
  "Gandaki": {
    "Kaski": ["Pokhara Metropolitan City", "Annapurna Rural Municipality", "Machhapuchhre Rural Municipality", "Madi Rural Municipality", "Rupa Rural Municipality"],
    "Syangja": ["Waling Municipality", "Putalibazar Municipality", "Bhirkot Municipality", "Phedikhola Rural Municipality", "Galyang Municipality", "Arjunchaupari Rural Municipality", "Biruwa Rural Municipality", "Harinas Rural Municipality", "Kaligandaki Rural Municipality", "Aandhikhola Rural Municipality"],
    "Parbat": ["Kushma Municipality", "Phalewas Municipality", "Bihadi Rural Municipality", "Jaljala Rural Municipality", "Mahashila Rural Municipality", "Modi Rural Municipality", "Painyu Rural Municipality"],
    "Baglung": ["Baglung Municipality", "Dhorpatan Municipality", "Burtibang Municipality", "Jaimuni Municipality", "Bareng Rural Municipality", "Nisikhola Rural Municipality", "Taman Khola Rural Municipality", "Tara Hill Rural Municipality"],
    "Myagdi": ["Beni Municipality", "Annapurna Rural Municipality", "Dhaulagiri Rural Municipality", "Mangala Rural Municipality", "Malika Rural Municipality", "Raghuganga Rural Municipality"],
    "Tanahun": ["Damauli Municipality", "Bhimad Municipality", "Byas Municipality", "Shuklagandaki Municipality", "Bandipur Rural Municipality", "Devghat Rural Municipality", "Ghiring Rural Municipality", "Rishing Rural Municipality", "Anbukhaireni Rural Municipality", "Myagde Rural Municipality"],
    "Lamjung": ["Besishahar Municipality", "Rainas Municipality", "Sundarbazar Municipality", "Dordi Rural Municipality", "Dudhpokhari Rural Municipality", "Kwholasothar Rural Municipality", "Marsyangdi Rural Municipality", "Madhya Nepal Municipality"],
    "Gorkha": ["Gorkha Municipality", "Palungtar Municipality", "Aarughat Rural Municipality", "Ajirkot Rural Municipality", "Barpak Sulikot Rural Municipality", "Bhimsen Rural Municipality", "Dharche Rural Municipality", "Gandaki Rural Municipality", "Sahid Lakhan Rural Municipality", "Siranchok Rural Municipality", "Tsum Nubri Rural Municipality"],
    "Mustang": ["Lomanthang Rural Municipality", "Lo-Ghekar Damodarkunda Rural Municipality", "Thasang Rural Municipality", "Gharapjhong Rural Municipality", "Waragung Muktikhsetra Rural Municipality"],
    "Manang": ["Manang Nisyang Rural Municipality", "Narpa Bhumi Rural Municipality", "Narphu Rural Municipality", "Chame Rural Municipality"]
  },
  "Lumbini": {
    "Rupandehi": ["Butwal Sub-Metropolitan City", "Tilottama Municipality", "Siddharthanagar Municipality", "Devdaha Municipality", "Sainamaina Municipality", "Marchawari Rural Municipality", "Rohini Rural Municipality", "Sammarimai Rural Municipality", "Kotahimai Rural Municipality", "Mayadevi Rural Municipality", "Omsatiya Rural Municipality", "Suddhodhan Rural Municipality", "Gaidahawa Rural Municipality", "Siyari Rural Municipality", "Kanchan Rural Municipality"],
    "Kapilbastu": ["Kapilbastu Municipality", "Banganga Municipality", "Buddhabhumi Municipality", "Krishnanagar Municipality", "Shivaraj Municipality", "Bijaynagar Rural Municipality", "Maharajgunj Rural Municipality", "Motipur Rural Municipality", "Suddhodhan Rural Municipality", "Yashodhara Rural Municipality"],
    "Nawalparasi East": ["Kawasoti Municipality", "Bulingtar Rural Municipality", "Devchuli Municipality", "Gaindakot Municipality", "Hupsekot Municipality", "Madhyabindu Municipality", "Baudimai Rural Municipality", "Binayi Tribeni Rural Municipality"],
    "Palpa": ["Tansen Municipality", "Rambha Rural Municipality", "Rainadevi Chhahara Rural Municipality", "Bagnaskali Rural Municipality", "Ribarban Rural Municipality", "Nisdi Rural Municipality", "Mathagadhi Rural Municipality", "Tinahu Rural Municipality", "Rampur Municipality"],
    "Pyuthan": ["Pyuthan Municipality", "Sworgadwary Municipality", "Jhimruk Rural Municipality", "Gaumukhi Rural Municipality", "Mallarani Rural Municipality", "Mandavi Rural Municipality", "Naubahini Rural Municipality", "Sarumarani Rural Municipality"],
    "Dang": ["Tulsipur Sub-Metropolitan City", "Ghorahi Sub-Metropolitan City", "Lamahi Municipality", "Rajpur Rural Municipality", "Babai Rural Municipality", "Banglachuli Rural Municipality", "Dangisharan Rural Municipality", "Gadhawa Rural Municipality", "Rapti Rural Municipality", "Shantinagar Rural Municipality"],
    "Rolpa": ["Rolpa Municipality", "Runtigadhi Rural Municipality", "Suwarnabati Rural Municipality", "Madi Rural Municipality", "Thabang Rural Municipality", "Triveni Rural Municipality", "Lungri Rural Municipality", "Duikholi Rural Municipality"],
    "Rukum East": ["Putha Uttarganga Rural Municipality", "Bhume Rural Municipality", "Sisne Rural Municipality"],
    "Arghakhanchi": ["Sandhikharka Municipality", "Bhumikasthan Municipality", "Panini Rural Municipality", "Shitaganga Rural Municipality", "Chhatradev Rural Municipality", "Malarani Rural Municipality"]
  },
  "Karnali": {
    "Surkhet": ["Birendranagar Municipality", "Bheriganga Municipality", "Gurbhakot Municipality", "Lekbesi Municipality", "Panchapuri Municipality", "Chaukune Rural Municipality", "Chingad Rural Municipality", "Barahtal Rural Municipality", "Simta Rural Municipality"],
    "Dailekh": ["Narayan Municipality", "Dullu Municipality", "Aathabis Municipality", "Bhagawatimai Rural Municipality", "Dungeshwar Rural Municipality", "Gurans Rural Municipality", "Mahabu Rural Municipality", "Naumule Rural Municipality", "Bhairabi Rural Municipality", "Thantikandh Rural Municipality"],
    "Jajarkot": ["Bheri Municipality", "Chhedagad Municipality", "Barekot Rural Municipality", "Junichande Rural Municipality", "Kuse Rural Municipality", "Nalgad Municipality", "Shiwalaya Rural Municipality", "Tribeni Rural Municipality"],
    "Dolpa": ["Thuli Bheri Municipality", "Tripurasundari Municipality", "Dolpo Buddha Rural Municipality", "Jagadulla Rural Municipality", "Mudkechula Rural Municipality", "She Phoksundo Rural Municipality", "Kaike Rural Municipality"],
    "Humla": ["Simkot Rural Municipality", "Adanchuli Rural Municipality", "Kharpunath Rural Municipality", "Namkha Rural Municipality", "Sarkegad Rural Municipality", "Tanjakot Rural Municipality", "Chankheli Rural Municipality"],
    "Mugu": ["Chhayanath Rara Municipality", "Khatyad Rural Municipality", "Mugum Karmarong Rural Municipality", "Soru Rural Municipality"],
    "Jumla": ["Chandannath Municipality", "Guthichaur Rural Municipality", "Hima Rural Municipality", "Kanakasundari Rural Municipality", "Patarasi Rural Municipality", "Sinja Rural Municipality", "Tatopani Rural Municipality", "Tila Rural Municipality"],
    "Kalikot": ["Raskot Municipality", "Tilagufa Municipality", "Pachaljharana Rural Municipality", "Palata Rural Municipality", "Naraharinath Rural Municipality", "Mahawai Rural Municipality", "Khandachakra Municipality", "Shubha Kalika Municipality"]
  },
  "Sudurpashchim": {
    "Kailali": ["Dhangadhi Sub-Metropolitan City", "Tikapur Municipality", "Bhajani Municipality", "Ghodaghodi Municipality", "Godawari Municipality", "Joshipur Rural Municipality", "Kailari Rural Municipality", "Chure Rural Municipality", "Bardagoriya Rural Municipality", "Gauriganga Municipality", "Janaki Rural Municipality", "Mohanyal Rural Municipality", "Phatababa Rural Municipality", "Suklaphanta Municipality", "Belauri Municipality"],
    "Kanchanpur": ["Mahendranagar Municipality", "Punarbas Municipality", "Belauri Municipality", "Shuklaphanta Municipality", "Bedkot Municipality", "Laljhadi Rural Municipality", "Krishnapur Municipality", "Bhimdatta Municipality"],
    "Dadeldhura": ["Amargadhi Municipality", "Aalital Rural Municipality", "Ajaymeru Rural Municipality", "Bhageshwar Rural Municipality", "Ganayapdhura Rural Municipality", "Nawadurga Rural Municipality", "Parashuram Municipality"],
    "Baitadi": ["Dasharathchand Municipality", "Patan Municipality", "Purchundi Rural Municipality", "Surnaya Rural Municipality", "Sigas Rural Municipality", "Melauli Municipality", "Dogdakedar Rural Municipality", "Dilasaini Rural Municipality", "Shivnath Rural Municipality", "Pancheshwar Rural Municipality"],
    "Bajhang": ["Jayaprithvi Municipality", "Thalara Rural Municipality", "Surma Rural Municipality", "Durgathali Rural Municipality", "Khandeshwari Rural Municipality", "Masta Rural Municipality", "Bungal Municipality", "Khaptad Chhanna Rural Municipality", "Kedarsyu Rural Municipality", "Chhapali Rural Municipality", "Wai Rural Municipality"],
    "Bajura": ["Badimalika Municipality", "Budhiganga Municipality", "Gaumul Rural Municipality", "Himali Rural Municipality", "Jagannath Rural Municipality", "Khaptad Chhanna Rural Municipality", "Pandusain Rural Municipality", "Swamikartik Khapar Rural Municipality", "Triveni Rural Municipality"],
    "Doti": ["Shikhar Municipality", "Dipayal Silgadhi Municipality", "K.I. Singh Rural Municipality", "Adharsha Rural Municipality", "Badikedar Rural Municipality", "Bogtan Fudsil Rural Municipality", "Jorayal Rural Municipality", "Purbichauki Rural Municipality", "Sayal Rural Municipality"],
    "Achham": ["Mangalsen Municipality", "Sanphebagar Municipality", "Ramaroshan Rural Municipality", "Bannigadhi Jayagadh Rural Municipality", "Chaurpati Rural Municipality", "Dhakari Rural Municipality", "Mellekh Rural Municipality", "Panchadewal Binayak Municipality", "Turmakhand Rural Municipality"]
  }
};

export const PROVINCES = Object.keys(NEPAL_DATA);

export function getDistricts(province) {
  if (!province || !NEPAL_DATA[province]) return [];
  return Object.keys(NEPAL_DATA[province]);
}

export function getMunicipalities(province, district) {
  if (!province || !district || !NEPAL_DATA[province] || !NEPAL_DATA[province][district]) return [];
  return NEPAL_DATA[province][district];
}